version: '3.8'

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - mongodb

  redis:
    image: redis:7.0.5
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - redis

  server:
    depends_on:
      - redis
      - mongodb
    build: ./server
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_PORT=${SERVER_PORT}

      - MONGO_URI=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongodb:27017/?authSource=windandwave
      - MONGO_DATABASE=${MONGO_APP_DATABASE}
    ports:
      - 4000:${SERVER_PORT}
    networks:
      - mongodb
      - redis
      - server

  client:
    depends_on:
      - server
    image: nginx:1.23.2
    restart: unless-stopped
    volumes:
      - ./client/dist:/usr/share/nginx/html/:ro
      - ./client.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

networks:
  mongodb:
    driver: bridge
  redis:
    driver: bridge
  server:
    driver: bridge

